# Introduction

Sir David Cox wrote: 

Donald Rubin formalized the no interference assumption into the formidable-sounding `Single Unit Treatment Value Assumption` (SUTVA).  This assumption incorporates the assumption of no-interference: the treatment or exposure of one unit does not affect the outcome of other units. Despite sporadic efforts, the research community gave little attention to this big assumption until the mid-aughts. Perhaps fueled by interest in causal inference and social network type data, recent advances relax the no-interference assumption and provide valid, unbiased causal effect estimators of direct and indirect effects. The conceptual framework developed by Hudgens, Halloran, Rosenbaum, Sobel, Tchetgen Tchetgen, and VanderWeele among others establishes an important basis for assessing causal effects in the presence of interference. (CITE)

`rinterference` is the first \lang{R} software package to program VTT's IPW estimators and the M-estimation method for estimating the variance. As of the current release, 

`rinterference` works only for binary outcomes and binary treatments. I have organized the paper with these headlines: 

Partial interference casts the assumption at the group level: cattle may pass a contagion within a herd but not between herds. Interference may occur within a group but not between groups (Sobel 2006, Hudgens and Halloran 2008). Halloran and Struchiner? (????) point out that this interference structure allows for identifiability of effect when data are randomized. When an experimenter randomizes units  - by design - at the group and individual levels, Hudgens and Halloran defined functions that, under certain assumptions described later, correctly estimate causal effects.

For observational data, on the other hand, Tchetgen Tchetgen and VanderWeele (2012) proposed inverse probability weight (IPW) estimators of causal effects based on group level propensity scores. They showed these estimators to be consistent and unbiased when the propensity score is known. Heydrich-Perez et al (2014) evaluated the finite-sample properties of these estimators when the propensity score is unknown and were the first to publish results using IPW-interference estimators on real data. H-P also formulated the variance estimators with unknown propensity scores using M-estimation (Stefanski and Boos ????). 


