## Estimators in `rinterference`
In most settings, only one potential outcome is observed per individual. Hence, what is known as the fundamental problem of causal inference CITE prevents estimating an individual's causal effects, but group and population level effects may be estimated without bias under certain conditions. Assuming no interference, Lunceford and Davidian (2005) explore the properties of estimators based on an individuals' propensity for treatment: inverse-probability-weighted (IPW), doubly robust (DR), and various stratification estimators. The IPW estimator essentially weights an individual's outcome by the inverse propensity; the DR estimator combines the inverse propensity with an outcome model; the stratification estimators group individuals into strata based on their propensity.

Thus far, only an IPW estimator's theoretical properties have been assessed when relaxing no interference to partial interference without randomization. Hong and Raudenbush and (someone else) did stratify ... Lan and Hudgens also have a unpublished manuscript modifying the DR estimator.  However, at this time, `rinterference` supports just an IPW estimator.