## The Basic Setup
Consider $N$ individuals clustered into $m$ groups, each with $n_i$ individuals for $i = 1, \dots, m$. $(Y_{ij}, A_{ij}, \mathbf{X}_{ij})$, represent the outcome, treatment, and matrix of baseline covariates, respectively, for each individual. Capitalized letters mark potential realizations; lowercase (e.g. $(y_{ij}, a_{ij}, \mathbf{x}_{ij})$) are observed or realized values. 

With a binary treatment, $A_{ij} \in \{0, 1\}$, the set $mathcal{A}(n_i)$ has $2^{n_i}$ elements and contains all of group $i$'s possible treatment assignments, generically labelled $\mathbf{A}_i = (A_{i1}, \dots, A_{in_i})$. Similarly, $\mathbf{A}_{i,-j} = (A_{i1}, \dots, A_{ij-1}, A_{ij+1, \dots, A_{in_i})$ represents a group's treatment assignment leaving out the $j$th subject.

$Y_{ij} = Y_{ij}(a_{ij}, \mathbf{a}_{i,-j}) = Y_{ij}(\mathbf{a}_i)$ is the potential outcome for an individual under the realized treatment assignment in group $i$. If we assume no interference occurs between groups, then a subject's potential outcome depends only on their group's treatment assignment. That is, $Y_{ij}(\mathbf{a}_i, \mathbf{a}_{i'}) = Y_{ij}(\mathbf{a}_i)$ for all $i' \neq i$.

In some cases, like the examples described in this paper, the study design includes both an experimental and observational (i.e. not randomized) component in assigning treatment. In the voting example, the experimenter randomly allocated group-level treatments (experimental); however, the individual's treatment depends on which of two household members opens the door (observational). As described below, `rinterference` allows for including an additional binary variable, $B_{ij}$, in the causal model. In both examples provided, this variable indicates the individual's participation in the study.