## Estimands
The individual's average potential outcome when assigned treatment $a$ under allocation $\alpha$ is an average of their potential outcomes under possible treatment assignments weighted by the probability of each treatment assignment. Specifically,

\[
\bar{y}_{ij}(a; \alpha) = E[Y(\mathbf{a}_{i, -j})] = \sum_{\mathbf{a}_{i, -j} \in \mathcal{A}}(n_i - 1) y_{ij}(a; \mathbf{a}_{i, -j}) \pi(\mathbf{a}_{i, -j}; \alpha).
\]

The marginal individual average potential outcome sums across an individual's potential outcomes for all group treatment vectors in $\mathcal{A}(n_i)$, thus averaging over all treatment options (footnote: see note in Direct Effects for possible confusion about the term 'marginal'):

\[
\bar{y}_{ij}(\alpha) = E(Y(\mathbf{a}_{i}) = \sum_{\mathbf{a}_{i} \in \mathcal{A}(n_i)} y_{ij}(\mathbf{a}_{i}) \pi(\mathbf{a}_{i}; \alpha).
\]

A simple mean of individual average potential outcomes within a cluster define group average potential outcomes. Likewise, population level estimands are means of the group level estimands. $\bar{y}_(a; \alpha) = \sum_{i = 1}^m \sum_{j = 1}^{n_i} \bar{y}_{ij}(a; \alpha)$ is the formula for a given treatment's estimand, while $\bar{y}_(\alpha) = \sum_{i = 1}^m \sum_{j = 1}^{n_i} \bar{y}_{ij}(\alpha)$ is the marginal population level estimand.
 
Differences in these potential outcome estimands define causal effects. HH describe four causal effects that can be identified when assuming partial interference: direct, indirect, total, and overall (see also TTV and others). 

### Direct Effects

An individual's average direct (or unit treatment) effect compares an individual's outcomes under one treatment ($a_{ij} = a_1$) to another ($a_{ij} = a_2$) for a specified coverage level $\alpha$:

\[
\bar{DE}_{ij}(\alpha) = \bar{Y}_{ij}(a_1, \alpha) - \bar{Y}_{ij}(a_2, \alpha). 
\].

Rubin (CITE) terms this a marginal causal effect because the estimand compares the expected values of the marginal distributions of $Y_{ij}(\mathbf{A}_{i, -j}, A_{ij} = a_1)$ and $Y_{ij}(\mathbf{A}_{i, -j}, A_{ij} = a_2)$. This will surely be confused with the meaning of 'marginal' effects used in `rinterference`, where marginal causal effects are defined as contrast of the marginal potential outcomes defined above.

Like average potential outcomes, means of individual direct effects define group and then population average direct effects: 
\[
\text{group: } \bar{DE}_i(\alpha) = \sum_{i = 1}^{n_i} \bar{DE}_{ij}(\alpha)/m \quad \text{population: } \bar{DE}(\alpha) = \sum_{i = 1}^m \bar{DE}_i(\alpha)/m
\]

### Indirect Effects

An indirect (or spillover) effect on an individual is the effect of others' treatment in the same group on that individual. In the vaccine example provided, this is the difference in potential outcomes under two different allocation schemes. It defined for both treated and untreated subjects.

\[
\bar{IE}_{ij}(\alpha, \alpha') = Y_{ij}(\mathbf{A}_{i, -j}, A_{ij} = a_1, \alpha) -  Y_{ij}(\mathbf{A}_{i, -j}, A_{ij} = a_1, \alpha') 
\]

\[
\text{group: } \bar{IE}_i(\alpha) = \sum_{i = 1}^{n_i} \bar{IE}_{ij}(\alpha, \alpha')/m \quad \text{population: } \bar{IE}(\alpha, \alpha') = \sum_{i = 1}^m \bar{IE}_i(\alpha, \alpha')/m
\]

Two notes about direct and indirect effects: Unfortunately, concepts of direct and indirect effects developed in both the literature on mediation and interference. They refer to different concepts, but mediation and interference may be present in the same problem. TTV suggests referring to interference direct effects as `unit-level treatment` effects and, like Sobel 2006 (CITE), interference indirect effects as `spillover` effects. Of course, `spillover` should not be confused with the concept in zoonotic disease studies. This author leaves it those above his pay-grade to sort out these issues and suggests German as a possible solution.

If the indirect effect equals zero, then interference is not present. However, the presence of interference tells you nothing about the mechanisms of interference. Ogburn and Vanderweele provide a good summary of types of interference, but researchers interested in disentangling type of interference should be prepared to go from the bleeding edge of causal inference to the uncut.

### Total Effect

\[
\bar{TE}_{ij}(\alpha, \alpha') = Y_{ij}(\mathbf{A}_{i, -j}, A_{ij} = a_1, \alpha) -  Y_{ij}(\mathbf{A}_{i, -j}, A_{ij} = a_2, \alpha') 
\]

\[
\text{group: } \bar{TE}_i(\alpha) = \sum_{i = 1}^{n_i} \bar{TE}_{ij}(\alpha, \alpha')/m \quad \text{population: } \bar{TE}(\alpha, \alpha') = \sum_{i = 1}^m \bar{TE}_i(\alpha, \alpha')/m
\]

### Overall Effect

\[
\bar{OE}_{ij}(\alpha, \alpha') = Y_{ij}(\alpha) -  Y_{ij}(\alpha') 
\]

\[
\text{group: } \bar{OE}_i(\alpha) = \sum_{i = 1}^{n_i} \bar{OE}_{ij}(\alpha, \alpha')/m \quad \text{population: } \bar{OE}(\alpha, \alpha') = \sum_{i = 1}^m \bar{OE}_i(\alpha, \alpha')/m
\]
