### IPW Point Estimators
In Section 5 of their paper, TTV propose Inverse Probability Weighting to estimate causal effects under interference in a non-randomized study design. Individuals' outcomes are weighted by the group-level propensity score, $P(\mathbf{A}_i | \mathbf{X}_i)$ -- the probability of a group's treatment assignment given the covariates of individuals in a group. Under the following assumptions, TTV showed the IPW estimators to be unbiased when the group-level propensities are known:

\begin{align*}
\text{Conditional Independence: } & P(\mathbf{A}_i = \mathbf{a}_i | \mathbf{X}_i, \mathbf{Y}_i) = P(\mathbf{A}_i = \mathbf{a}_i | \mathbf{X}_i) \\
\text{Positivity: } & P(\mathbf{A}_i = \mathbf{a}_i | \mathbf{X}_i) > 0 \quad \forall \mathbf{a}_i \in \mathcal{A}(n_i) \\
\end{align*}.

Of course in general, propensity scores will not be known and must be estimated. TTV suggest random effects models to estimate $P(\mathbf{A}_i | \mathbf{X}_i; \boldsymbol{\theta}) = f_{\mathbf{A}_i | \mathbf{X}_i}(\mathbf{A}_i | \mathbf{X}_i; \boldsymbol{\theta}_x, \theta_s)$, where $\boldsymbol{\theta}_x$ represents the fixed effects parameters and $\theta_s$ group random effect parameters. For a binary outcome, for example, a model for the group's propensity score could be:

\[
f_{\mathbf{A}_i | \mathbf{X}_i}(\mathbf{A}_i | \mathbf{X}_i; \boldsymbol{\theta}_x, \theta_s) = \int \prod_{j = 1}^{n_i} h_{ij}(b_i); \boldsymbol{\theta}_x)^{A_{ij}} (1 - h_{ij}(b_i); \boldsymbol{\theta}_x)^{1 - A_{ij}}) f_b(b_i; \boldsymbol{\theta}_s) db_i 
\]

where $h_{ij}(b_i); \boldsymbol{\theta}_x) = P(A_{ij} = 1 | \mathbf{X}_{ij}, b_i, \boldsymbol{\theta}_x) = logit^{-1}(\mathbf{X}_{ij}\boldsymbol{\theta}_x + b_i)$. 
In `rinterference` the group-level propensity defaults to the $f_{\mathbf{A}_i | \mathbf{X}_i}(\mathbf{A}_i | \mathbf{X}_i; \boldsymbol{\theta}_x, \theta_s)$ defined here. While this model describes a variety of situations, the propensity function should be carefully considered per research problem. As shown in the examples below, an important feature of `rinterference` is that analysts may create their own propensity function via the `propensity_integrand` argument.

Once the details of group propensity estimation are worked out, the IPW estimators for the group-level potential outcomes are straightforward:
\begin{equation}
\widehat{Y}^{ipw}(a, \alpha) \equiv \frac{\sum_{j = 1}^{n_i} \pi_i(\mathbf{A}_{i, -j}; \alpha) I(A_{ij} = a) Y_{ij}(\mathbf{A}_{ij}) }{n_i \times f_{\mathbf{A}_i | \mathbf{X}_i}(\mathbf{A}_i | \mathbf{X}_i; \boldsymbol{\theta})   }
\end{equation}

\begin{equation}
\widehat{Y}^{ipw}(\alpha) \equiv \frac{\sum_{j = 1}^{n_i} \pi_i(\mathbf{A}_{i}; \alpha) Y_{ij} }{n_i \times f_{\mathbf{A}_i | \mathbf{X}_i}(\mathbf{A}_i | \mathbf{X}_i; \boldsymbol{\theta})   }
\end{equation}

From these, we construct population level average potential outcomes and marginal population level average potential outcomes as $\widehat{Y}^{ipw}(a; \alpha) = \sum__{i = 1}^m \widehat{Y}_i^{ipw}(a; \alpha)$ and $\widehat{Y}^{ipw}(\alpha) = \sum__{i = 1}^m \widehat{Y}_i^{ipw}(\alpha)$. Estimators for direct, indirect, total, and overall effects merely contrast group or population estimates: 

\begin{align}
\widehat{DE}(\alpha) &= \widehat{Y}^{ipw}(a_1; \alpha) - \widehat{Y}^{ipw}(a_2; \alpha)  \\
\widehat{IE}(\alpha, \alpha') &= \widehat{Y}^{ipw}(a_1; \alpha) - \widehat{Y}^{ipw}(a_1; \alpha')  \\
\widehat{TE}(\alpha, \alpha') &= \widehat{Y}^{ipw}(a_1; \alpha) - \widehat{Y}^{ipw}(a_2; \alpha')  \\
\widehat{OE}(\alpha, \alpha') &= \widehat{Y}^{ipw}(\alpha) - \widehat{Y}^{ipw}(\alpha')  \\
\end{align}
