### IPW Variance Estimation

Web Appendix A to PH 2014 (CITE) derives asymptotic distributions for the IPW estimators using M-estimation theory. In the interest of space, I refer the interested reader to this source (PROVIDE LINK) for complete details. I have attempted to keep the notation in this paper similar to the web appendix.

Briefly, when the propensity score is known, the large sample variance of, for example, $\widehat{DE}(\alpha) is

\[
\frac{1}{m^2}\sum{i = 1}^m \left\{\widehat_i(\alpha) - \widehat(DE)(\alpha) \right\}^2
\].

Results for $\widehat{Y}^{ipw}$, $\widehat{IE}$, $\widehat{TE}$, and $\widehat{OE}$ are defined analogously. When the `variance_estimation` argument is set to `simple' in `interference()`, `rinterference` uses this formula to compute the standard errors and confidence intervals. 

With an estimated propensity score, the math requires derivatives of the propensity with respect to each parameter and the scores of the loglihood of the mixed model. Again, PH's web appendix A contains the details, but this method is available with the `robust` option to the `variance_estimation` argument.

